class SubscribeController < ApplicationController
  def create
    # When registering the app on Slack, the server must reply with the challenge parameter
    event = params[:event]
    if params[:challenge].present?
      return render json: {challenge: params[:challenge]}
    elsif event.nil?
      return render json: {}, status: 401
    end
    
    # TODO: verify Slack secret

    # Skip messages that are generated by this bot
    unless event[:bot_id] || event[:subtype]
      case event[:text].downcase
      when 'go'
        FaceMatch::SlackHelper.play(event[:user], event[:channel])
      when 'help'
        FaceMatch::SlackHelper.help event[:channel]
      end
    end

    render json: {}
  end
end
